name: 'Install Wren Console'
description: 'Install Wren Console CLI tool'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
branding:
  icon: package
  color: blue
runs:
  using: "composite"
  steps:
    - name: Checkout wren-console
      uses: actions/checkout@v2
      with:
        repository: joshgoebel/wren-console
        path: wren-console
        ref: v0.3.1
    - name: Pin dependencies
      shell: bash
      run: |
        cat wren-console/WREN_ESSENTIALS >> $GITHUB_ENV
    - name: Checkout wren-essentials
      uses: actions/checkout@v2
      with:
        repository: joshgoebel/wren-essentials
        path: wren-console/deps/wren-essentials
        ref: ${{env.WREN_ESSENTIALS}}
    - name: Build wren-console
      shell: bash
      run: |
        cd wren-console
        make -j4 -C projects/make/
        mkdir -p $GITHUB_WORKSPACE/usr/bin
        cp bin/wrenc $GITHUB_WORKSPACE/usr/bin
        echo "$GITHUB_WORKSPACE/usr/bin" >> $GITHUB_PATH

